module.exports = {
  emojis: [
    {
      id: 1,
      textContent: "text",
      date: "2020-02-02",
      emotionId: 1,
      createdAt: "created time",
      updatedAt: "updated time",
      text_status: 1,
      emotion_count: 2,
    },
    {
      id: 2,
      textContent: "text",
      date: "2020/02/02",
      emotionId: 1,
      createdAt: "created time",
      updatedAt: "updated time",
      text_status: 1,
      emotion_count: 2,
    },
    {
      id: 3,
      textContent: "text",
      date: "2020/02/02",
      emotionId: 3,
      createdAt: "created time",
      updatedAt: "updated time",
      text_status: 1,
      emotion_count: 2,
    },
    {
      id: 4,
      textContent: "text",
      date: "2020/02/02",
      emotionId: 3,
      createdAt: "created time",
      updatedAt: "updated time",
      text_status: 1,
      emotion_count: 2,
    },
    {
      id: 5,
      textContent: "text",
      date: "2020/02/02",
      emotionId: 4,
      createdAt: "created time",
      updatedAt: "updated time",
      text_status: 1,
      emotion_count: 1,
    },
  ],
};
